[package]
name = "relineate"
version = "0.1.0"
authors = ["Dan Shick <dan.shick@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
byteorder = "1"
num_enum = "0.5"
svg = "0.8.0"
